// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIghJx7VkeANVc4MkOp5R9LIdr52Ryq5o',
    appId: '1:1008121233833:web:3226f85b40975bcfd284b8',
    messagingSenderId: '1008121233833',
    projectId: 'care-pat',
    authDomain: 'care-pat.firebaseapp.com',
    databaseURL: 'https://care-pat-default-rtdb.firebaseio.com',
    storageBucket: 'care-pat.appspot.com',
    measurementId: 'G-XWGCLLX8NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbEJa4tkT3ForXk7hEHpln9xmAZSGvBI',
    appId: '1:1008121233833:android:6faa9182031b4729d284b8',
    messagingSenderId: '1008121233833',
    projectId: 'care-pat',
    databaseURL: 'https://care-pat-default-rtdb.firebaseio.com',
    storageBucket: 'care-pat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWSp3wmCXB1qS405Eo9jdhd6GY_r4vk8',
    appId: '1:1008121233833:ios:d8c31dbd83d9ed2dd284b8',
    messagingSenderId: '1008121233833',
    projectId: 'care-pat',
    databaseURL: 'https://care-pat-default-rtdb.firebaseio.com',
    storageBucket: 'care-pat.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWSp3wmCXB1qS405Eo9jdhd6GY_r4vk8',
    appId: '1:1008121233833:ios:d8c31dbd83d9ed2dd284b8',
    messagingSenderId: '1008121233833',
    projectId: 'care-pat',
    databaseURL: 'https://care-pat-default-rtdb.firebaseio.com',
    storageBucket: 'care-pat.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIghJx7VkeANVc4MkOp5R9LIdr52Ryq5o',
    appId: '1:1008121233833:web:d0817c61df0c4243d284b8',
    messagingSenderId: '1008121233833',
    projectId: 'care-pat',
    authDomain: 'care-pat.firebaseapp.com',
    databaseURL: 'https://care-pat-default-rtdb.firebaseio.com',
    storageBucket: 'care-pat.appspot.com',
    measurementId: 'G-SE0D4J0QZ6',
  );

}